### ISSUE TITLE
Problem With 1.10.2 Versions

### ISSUE THREAD

**Issue by co221133** [ItzDennisz/Enhanced-Items#7]
Hey guys. Sorry to bother you (really, I am) but I'm having some trouble getting this plugin to work on my 1.10.2 server. Unfortunately, updating to 1.11 isn't an option, due to all of the other plugins I have that haven't yet updated, but this plugin is exactly what I've been looking for, for a very long time.

Whenever I download the most recent version of the plugin, /eitems and all of its sub-commands don't do anything, either directly from me or the console. There's no error, and there's no message saying the command doesn't exist; it just doesn't do anything at all.

I tried to download a previous version of the plugin, before it was updated to 1.11, and that got the commands to work (and the items.yml to generate, which the most recent version didn't do). Except, when I made an item, and tried to use /eitem give, it started shooting off errors in the console, whether I typed it, or typed it from the console itself.

The error message I got is in the attached .txt file.
[ErrorMessage.txt](https://github.com/ItzDennisz/Enhanced-Items/files/802476/ErrorMessage.txt)

Edit: And while I'm asking for help, I feel I may as well clarify, in order to use custom item IDs for resource packs, do I just need to name the texture the same ID I put in the items.yml folder? For instance, assets/minecraft/textures/items/itemIDnumber?

Thanks so much for any help you can offer me, guys. I appreciate it.

**Comment by ItzDennisz** [comment]
Hi, please stand by while I take a look at the issue.

**Comment by ItzDennisz** [comment]
Though you are using an outdated version, I have tested the newest version but it still does not work.
The fix needed for this however is so small that I am willing to create a patch just for you.
I will finish up some things I have been working on before uploading the patch, so please stand by.

In order to get the plugin to work on versions lower than 1.11, you need to disable safety mode in the config.yml. Note however that if you do, certain features may not work properly and you will get no support if this happens.

Good luck!

**Comment by ItzDennisz** [comment]
Patch uploaded. Issue should be fixed.
